### ISSUE TITLE
Distance for Longitude Calculation

### ISSUE THREAD

**Issue by BeaconSlash** [drchuck59/SCTBuilder#43]
Hi again,

Generated new data with the tool.

Selection Square values were:
North - N045.25.00.000
West - W096.00.00.000
South - N038.50.00.000
East - N082.48.00.000

Centering Coordinates were set as N042.07.30.000 W089.24.00.000 after clicking on "Center on square" button.

VRC Info output file generated the following:

[INFO]
ZAU_2102
ZAU_xx_OBS
KORD
N042.07.30.000
W089.24.00.000
60
51.3
3
1

The 51.3 value for NM per Degree Longitude appears incorrect.

Geo Calculator at http://edwilliams.org/gccalc.htm indicates a value of 44.65 NM per degree longitude for the given latitude. 44.65 appears to be approximately correct after measuring a 1° line on Google Earth at approximately the same latitude.

Thank you for your work with this tool!

**Comment by drchuck59** [comment]
Nice pickup!  Most wouldn't notice that I calculate this distance at an average 10,000 feet AGL, not at MSL!  This distance corrects for altitude (but I'll go back and check it again).  Since the earth is a spheroid and not a sphere, there is no perfect calculation (although most use the one you reference).  

Shorter distances (e.g., the Ruler function) use simple trigonometry, not the Haversine formula.  (My software uses Haversine for anything over 200 NM because the error exceeds 1% around that value.)  

Thus the "Longitude miles" value has no impact to distance calculations in VRC or vSTARS.  The only real impact is how much "stretch" you want laterally on your screen; experiment with values up to 70.  At ZJX, 59.4 gave the best appearance for ZJX.

**Comment by drchuck59** [comment]
Your second question was about the "margins."  Some FEs prefer to use the limits of their ARTCC then arbitrarily extend those limits by a number of miles.  Those values can be entered in lieu of entering the actual coordinates by entering miles, and the software will calculate the new margin coordinates.  Like you, I select the two coordinates and ignore the margin feature.

**Comment by BeaconSlash** [comment]
> Thus the "Longitude miles" value has no impact to distance calculations in VRC or vSTARS. The only real impact is how much "stretch" you want laterally on your screen; experiment with values up to 70. At ZJX, 59.4 gave the best appearance for ZJX.

This is probably not the best forum to discuss geodetic calculations and such, but suffice it to say that the program's calculated NM/° Longitude value generated a visual sufficiently different/stretched from that which I normally observe at work that I believe it to be significantly erroneous.

**Comment by drchuck59** [comment]
I've updated the calculation - it should be more accurate now.  However, as it only controls the "stretch" of the screen, it may appear odd using that value.
